// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlaygroundDotNetAPI.Data;

#nullable disable

namespace PlaygroundDotNetAPI.Migrations
{
    [DbContext(typeof(MyDbContextSqLite))]
    [Migration("20240904173214_CharmanderLine")]
    partial class CharmanderLine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("PlaygroundDotNetAPI.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pokedex");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bulbasaur"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ivysaur"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Venusaur"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Charmander"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Charmeleon"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Charizard"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
