# https://github.com/marketplace/actions/build-and-push-docker-images
name: "Docker"

on:
  workflow_call:

jobs:
  azure_deploy:
    name: "Deploy to Azure"
    runs-on: ubuntu-latest
    env:
      DOTNET_CORE_VERSION: 8.0.x
      CONTAINER_APP_NAME: playdotnetapi-container-app
      CONTAINER_APP_ENVIRONMENT_NAME: managedEnv20240830130926
      RESOURCE_GROUP: DefaultResourceGroup-SUK
      CONTAINER_REGISTRY_NAME: registry20240830131312
      CONTAINER_REGISTRY_LOGIN_SERVER: registry20240830131312.azurecr.io
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.managedEnv20240830130926_SPN }}

      - name: Container App deploy
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
          acrUsername: ${{ secrets.registry20240830131312_USERNAME_69F7 }}
          acrPassword: ${{ secrets.registry20240830131312_PASSWORD_69F7 }}
          imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}