# https://github.com/marketplace/actions/build-and-push-docker-images
name: "Docker"
  
on:
  workflow_call:

jobs:
  dockerization:
    name: "Docker"
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PERSONAL_ACCESS_TOKEN }}

      # TODO: turn off artifact uploading conditionally
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: craigiswayne/playground-dotnet-api:latest
          secrets: |
            "my_secret=${{ secrets.MY_SECRET }}"