# https://github.com/marketplace/actions/build-and-push-docker-images
name: "Docker"

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  dockerization:
    name: "Docker"
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Sekrit
        shell: bash
        run: |
          echo "${{ secrets.DOCKERHUB_USERNAME }}"
          echo "${{ secrets.DOCKERHUB_PASSWORD }}"

#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # TODO: turn off artifact uploading conditionally
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: craigiswayne/playground-dotnet-api:latest
          secrets: |
            "my_secret=${{ secrets.MY_SECRET }}"
            
      - name: Create Build Artifact
#        if:  github.ref == 'refs/heads/develop'
        uses: actions/upload-artifact@v4
        with:
          name: build-${{env.UNIQUE_ID}}
          path: ${{env.PUBLISH_PATH}}