# https://github.com/marketplace/actions/build-and-push-docker-images
name: "Dockerization"

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  dockerization:
    name: "Dockerization"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: craigiswayne/playground-dotnet-api:latest