name: "Deploy"

on:
  deployment:

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  dotnet:
    uses: './.github/workflows/_dotnet.yml'
    secrets: inherit
    with:
      project_path: 'PlaygroundDotNetAPI/PlaygroundDotNetAPI.csproj'
      test: true
#      environment: 'production'