name: "Deploy to Staging"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        required: true
        options:
          - staging
          - production

jobs:
  dotnet_build_and_test:
    uses: './.github/workflows/_dotnet.yml'
    with:
      project_path: 'PlaygroundDotNetAPI/PlaygroundDotNetAPI.csproj'
      test: false
      publish: false
      environment: staging

  dockerization:
    needs: [ dotnet_build_and_test ]
    uses: './.github/workflows/_dockerization.yml'
    secrets: inherit