name: Main

on:
  push:
    branches:
      - main
      - develop
      - feature/overriding-appsettings-with-environment-variables
    paths-ignore:
      - '**/*.md'
  pull_request:
    types: [opened, reopened, edited]
    branches: [develop]

permissions:
  id-token: write
  contents: read

jobs:
  dotnet_build_and_test:
    uses: './.github/workflows/_dotnet.yml'
    secrets: inherit
    with:
      project_path: 'PlaygroundDotNetAPI/PlaygroundDotNetAPI.csproj'
      test: true
      environment: 'production'

  dotnet_staging:
    uses: './.github/workflows/_dotnet.yml'
    secrets: inherit
    with:
      project_path: 'PlaygroundDotNetAPI/PlaygroundDotNetAPI.csproj'
      test: true
      environment: 'staging'

  dockerization:
    needs: [ dotnet_build_and_test ]
    uses: './.github/workflows/_dockerization.yml'
    secrets: inherit

  azure_infrastructure:
    name: "Infrastructure on Azure"
    needs: [ dotnet_build_and_test ]
    uses: './.github/workflows/_azure-infrastructure.yml'
    secrets: inherit

  azure_deploy:
    name: "Deploy to Azure"
    needs: [ azure_infrastructure ]
    uses: './.github/workflows/_azure-deploy.yml'
    secrets: inherit