name: Main

on:
  push:
    branches:
      - main
      - develop
      - feature/refactor-workflows
    paths-ignore:
      - '**/*.md'
  pull_request:
    types: [opened, reopened, edited]
    branches: [develop]

permissions:
  id-token: write
  contents: read

jobs:
  dotnet:
    uses: './.github/workflows/_dotnet.yml'
    secrets: inherit

  dockerization:
    needs: [ dotnet ]
    uses: './.github/workflows/_dockerization.yml'
    secrets: inherit

  azure_infrastructure:
    name: "Infrastructure on Azure"
    needs: [ build_and_test ]
    uses: './.github/workflows/_azure-infrastructure.yml'
    secrets: inherit

  azure_deploy:
    name: "Deploy to Azure"
    needs: [ azure_infrastructure ]
    uses: './.github/workflows/_azure-deploy.yml'
    secrets: inherit